EconomicManagement/EconomicManagementAPP/Controllers/AccountTypesController.cs
using EconomicManagementAPP.Models;
using Microsoft.AspNetCore.Mvc;
using EconomicManagementAPP.Interface;

namespace EconomicManagementAPP.Controllers
{
    public class AccountTypesController : Controller
    {
        private readonly IRepositorieAccountTypes repositorieAccountTypes;
        private readonly IRepositorieUsers repositorieUsers;

        public AccountTypesController(IRepositorieAccountTypes repositorieAccountTypes, IRepositorieUsers repositorieUsers)
        {
            this.repositorieAccountTypes = repositorieAccountTypes;
            this.repositorieUsers = repositorieUsers;
        }

        // Creamos index para ejecutar la interfaz
        public async Task<IActionResult> Index()
        {
            if (UsersController.valorSesion is null)
            {
                return RedirectToAction("Login", "Users");
            }
            var userId = UsersController.valorSesion.Id;
            Console.WriteLine("hola soy el user id " + userId);
            var accountTypes = await repositorieAccountTypes.GetAccountsTypes(userId);
            return View(accountTypes);
        }
        public IActionResult Create()
        {
            if (UsersController.valorSesion is null)
            {
                return RedirectToAction("Login", "Users");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AccountTypes accountTypes)
        {
            if (!ModelState.IsValid)
            {
                return View(accountTypes);
            }

            accountTypes.UserId = UsersController.valorSesion.Id; ;
            accountTypes.OrderAccount = 1;

            // Validamos si ya existe antes de registrar
            var accountTypeExist =
               await repositorieAccountTypes.Exist(accountTypes.Name, accountTypes.UserId);

            if (accountTypeExist)
            {
                // AddModelError ya viene predefinido en .net
                // nameOf es el tipo del campo
                ModelState.AddModelError(nameof(accountTypes.Name),
                    $"The account {accountTypes.Name} already exist.");

                return View(accountTypes);
            }
            accountTypes.DbStatus = true;
            int newId = await repositorieAccountTypes.Create(accountTypes);
            // Redireccionamos a la lista
            return RedirectToAction("Create", "Accounts", new { id=newId });
        }

        // Hace que la validacion se active automaticamente desde el front
        [HttpGet]
        public async Task<IActionResult> VerificaryAccountType(string Name)
        {
            var userId = UsersController.valorSesion.Id;
            var accountTypeExist = await repositorieAccountTypes.Exist(Name, userId);

            if (accountTypeExist)
            {
                // permite acciones directas entre front y back
                return Json($"The account {Name} already exist");
            }

            return Json(true);
        }

        //Actualizar
        [HttpGet]
        public async Task<ActionResult> Modify(int id)
        {
            if (UsersController.valorSesion is null)
            {
                return RedirectToAction("Login", "Users");
            }
            var userId = UsersController.valorSesion.Id;
            var accountType = await repositorieAccountTypes.GetAccountById(id, userId);

            if (accountType is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(accountType);
        }
        [HttpPost]
        public async Task<ActionResult> Modify(AccountTypes accountTypes)
        {
            var userId = UsersController.valorSesion.Id;
            var accountType = await repositorieAccountTypes.GetAccountById(accountTypes.Id, userId);

            if (accountType is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieAccountTypes.Modify(accountTypes);// el que llega
            return RedirectToAction("Index","Home");
            
        }
        // Eliminar
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (UsersController.valorSesion is null)
            {
                return RedirectToAction("Login", "Users");
            }
            var userId = UsersController.valorSesion.Id;
            var account = await repositorieAccountTypes.GetAccountById(id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            account.NumberAccount = await repositorieAccountTypes.GetNumberAccount(id);
           
            return View(account);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAccount(int id)
        {
            var userId = UsersController.valorSesion.Id;
            var account = await repositorieAccountTypes.GetAccountById(id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            var account_Type = await repositorieAccountTypes.ExistingAccountType(id);

            if (account_Type == false)
            {
                await repositorieAccountTypes.Delete(id);
                return RedirectToAction("Index", "Home");
            }

            await repositorieAccountTypes.DeleteModify(id);
            return RedirectToAction("Index","Home");
        }
    }
}

EconomicManagement/EconomicManagementAPP/Views/Shared/_Layout.cshtml
@using EconomicManagementAPP.Controllers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["title"] - EconomicManagementAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-appd-version="true" />
    <link rel="stylesheet" href="~/css/AccorddionStyles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EconomicManagementAPP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Economic Management</a>
                <span class="spacer"></span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (UsersController.valorSesion is not null)
                        {
                           
                            <li class="nav-item">
                                @*apuntamos al controller asp-controller="AccountTypes" y al view asp-action="Index"*@
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <span class="headerSpacer"></span>
                          
                            <li class="nav-item">
                                <a  asp-area="" title="Modify" asp-controller="Users" asp-action="Modify">
                                    <img src="../../img/edit-profile.png" width="40" height="35" alt="Profile"/>
                                </a>
                            </li>
                            <li class="nav-item">
                                @*apuntamos al controller asp-controller="AccountTypes" y al view asp-action="Index"*@
                                <a asp-area="" asp-controller="Users" asp-action="LogOut">
                                    <img class="logout" src="../../img/cerrar-sesion.png" width="35" height="35">
                                    </a>
                            </li>
                        }
                        else
                        {
                            <span class="headerSpacer"></span>
                            <li class="nav-item">
                                @*apuntamos al controller asp-controller="AccountTypes" y al view asp-action="Index"*@
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Create">Sign up</a>
                            </li>
                            <li class="nav-item">
                                @*apuntamos al controller asp-controller="AccountTypes" y al view asp-action="Index"*@
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">
                                    <img src="../../img/login.png" width="25" height="25">
                                    Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-dark">
        <div class="container ">
            &copy; 2022 - Developed by JeniferPadilla
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>